### ISSUE TITLE
Feature Request - Unit of Measure

### ISSUE THREAD

**Issue by Gliebig** [tango2590/Hughes-Power-Watchdog#4]
I tried the BLE scanner from bluepixel technologoes and the Nordic nRF connect scanners on my Samsung Galaxy Note 9. It was quite easy to find the MAC address once I was able to isolate the device and know what I was looking for. I have the 30 amp version of the Hughes Power Watchdog. Not sure if that is why the prefix is different. Mine begins with PMS... (maybe single line?) Once I got that figured out and reconfigured your yaml it worked straight away! I'm no expert, but do enjoy solving problems. I agree the energy reset feature would be great. Also, there are limits that can be set on my watchdog including Max Energy (kWh), Min and Max Voltages, and Max Amps. Those limits aren't as important with the integration into HA, but if they were able to be synced it might prove helpful when the ESP32 is not connected to it. Just a thought.

Since these devices are usually used on RV's, it might be helpful in your YAML to include the unit_of_measurement. I also monitor dc volts and all my sensor data is stored in an InfluxBD and graphed with Grafana. The "V" identifier isn't descriptive enough pulling out voltage measurements. Just might help out those that just copy and paste.  Great job!

````
sensor:`
  - platform: hughes_power_watchdog
    ble_client_id: power_watchdog
    voltage_line_1:
      name: "Watchdog Voltage Line 1"
      unit_of_measurement: "Vac"
      accuracy_decimals: 0
    current_line_1:
      name: "Watchdog Current Line 1"
      unit_of_measurement: "A"
      accuracy_decimals: 1
````
     
I use the following standard:
      unit_of_measurement: "A" Amps
      unit_of_measurement: "Vac" Volts Alternating Current
      unit_of_measurement: "Vdc: Volts Direct Current
